/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    5GTechnoPage: typeof import('./src/components/education/subject/5GTechnoPage.vue')['default']
    Apprenticeship: typeof import('./src/components/experience/Apprenticeship.vue')['default']
    BackButton: typeof import('./src/components/education/subject/elements/BackButton.vue')['default']
    CloudComputingPage: typeof import('./src/components/education/subject/CloudComputingPage.vue')['default']
    Conclusion: typeof import('./src/components/Conclusion.vue')['default']
    ContactButton: typeof import('./src/components/personnel/ContactButton.vue')['default']
    Education: typeof import('./src/components/Education.vue')['default']
    EmbeddedAIPage: typeof import('./src/components/education/subject/EmbeddedAIPage.vue')['default']
    EnergyConnectedObjects: typeof import('./src/components/education/subject/EnergyConnectedObjects.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    FiveGTechnoPage: typeof import('./src/components/education/subject/FiveGTechnoPage.vue')['default']
    Formation: typeof import('./src/components/Formation.vue')['default']
    Freelance: typeof import('./src/components/experience/Freelance.vue')['default']
    ImageSubject: typeof import('./src/components/education/subject/elements/ImageSubject.vue')['default']
    InnoProjectPage: typeof import('./src/components/education/subject/InnoProjectPage.vue')['default']
    Internship2023: typeof import('./src/components/experience/Internship2023.vue')['default']
    Internship2024: typeof import('./src/components/experience/Internship2024.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    MiddlewarePage: typeof import('./src/components/education/subject/MiddlewarePage.vue')['default']
    PDFReader: typeof import('./src/components/education/subject/elements/PDFReader.vue')['default']
    Personal: typeof import('./src/components/Personal.vue')['default']
    Portfolio: typeof import('./src/components/education/subject/Portfolio.vue')['default']
    PortfolioPage: typeof import('./src/components/education/subject/PortfolioPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityIoTPage: typeof import('./src/components/education/subject/SecurityIoTPage.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SkillMatrix: typeof import('./src/components/education/subject/elements/SkillMatrix.vue')['default']
    SmartDevicesPage: typeof import('./src/components/education/subject/SmartDevicesPage.vue')['default']
    TimelineEducation: typeof import('./src/components/personnel/TimelineEducation.vue')['default']
    TimelineFormation: typeof import('./src/components/personnel/TimelineFormation.vue')['default']
    TitlesSubject: typeof import('./src/components/education/subject/elements/TitlesSubject.vue')['default']
    TitleSubject: typeof import('./src/components/education/subject/elements/TitleSubject.vue')['default']
    WirelessCommPage: typeof import('./src/components/education/subject/WirelessCommPage.vue')['default']
    WSNPage: typeof import('./src/components/education/subject/WSNPage.vue')['default']
  }
}
