/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/education/subject/elements/BackButton.vue')['default']
    CloudComputingPage: typeof import('./src/components/education/subject/CloudComputingPage.vue')['default']
    ContactButton: typeof import('./src/components/personnel/ContactButton.vue')['default']
    Education: typeof import('./src/components/Education.vue')['default']
    EmbeddedAIPage: typeof import('./src/components/education/subject/EmbeddedAIPage.vue')['default']
    EnergyConnectedObjects: typeof import('./src/components/education/subject/EnergyConnectedObjects.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    Formation: typeof import('./src/components/Formation.vue')['default']
    ImageSubject: typeof import('./src/components/education/subject/elements/ImageSubject.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    PDFReader: typeof import('./src/components/education/subject/elements/PDFReader.vue')['default']
    Personal: typeof import('./src/components/Personal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityIoTPage: typeof import('./src/components/education/subject/SecurityIoTPage.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SmartDevicesPage: typeof import('./src/components/education/subject/SmartDevicesPage.vue')['default']
    TimelineEducation: typeof import('./src/components/personnel/TimelineEducation.vue')['default']
    TimelineFormation: typeof import('./src/components/personnel/TimelineFormation.vue')['default']
    TitlesSubject: typeof import('./src/components/education/subject/elements/TitlesSubject.vue')['default']
    TitleSubject: typeof import('./src/components/education/subject/elements/TitleSubject.vue')['default']
    WSNPage: typeof import('./src/components/education/subject/WSNPage.vue')['default']
  }
}
