/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/formation/subject/elements/BackButton.vue')['default']
    CloudComputingPage: typeof import('./src/components/formation/subject/CloudComputingPage.vue')['default']
    EmbeddedAIPage: typeof import('./src/components/formation/subject/EmbeddedAIPage.vue')['default']
    EnbeddedAI: typeof import('./src/components/formation/subject/EnbeddedAI.vue')['default']
    EnbeddedAIPage: typeof import('./src/components/formation/subject/EnbeddedAIPage.vue')['default']
    EnergyConnectedObjects: typeof import('./src/components/formation/subject/EnergyConnectedObjects.vue')['default']
    Experience: typeof import('./src/components/Experience.vue')['default']
    Formation: typeof import('./src/components/Formation.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    PDFReader: typeof import('./src/components/formation/subject/elements/PDFReader.vue')['default']
    Personal: typeof import('./src/components/Personal.vue')['default']
    Personnal: typeof import('./src/components/Personnal.vue')['default']
    Personnel: typeof import('./src/components/Personnel.vue')['default']
    PFormation: typeof import('./src/components/personnel/PFormation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityIoTPage: typeof import('./src/components/formation/subject/SecurityIoTPage.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/SiteHeader.vue')['default']
    SmartDevicesPage: typeof import('./src/components/formation/subject/SmartDevicesPage.vue')['default']
    TimelineFormation: typeof import('./src/components/personnel/TimelineFormation.vue')['default']
    WSNPage: typeof import('./src/components/formation/subject/WSNPage.vue')['default']
  }
}
